---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
sections:
- type: directory
  label: Data
  path: _data
  match: "*.yml"
  new_doc_ext: ".yml"
  create: all
- type: directory
  label: Menu
  path: _data
  match: "*.csv"
  new_doc_ext: ".csv"
  create: all  
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - default
- type: directory
  path: _people
  label: People
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "*"
  templates:
  - project
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
